Tdl 6624 adding comments stream
singer-io/tap-chargebee pull request #52
Opened 2021-06-10 05:27 UTC by dbshah1212

# Description of change
Added support of comments stream

# Manual QA steps
 - Run discovery and sync mode, getting valid records and start date is also working properly for comments stream
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-06-10 08:08 UTC, savan-chovatiya approved these changes

2021-06-22 10:29 UTC, karanpanchal-crest approved these changes

2021-07-22 17:54 UTC, luandy64 requested changes

2021-07-22 17:54 UTC, luandy64 commented on tap_chargebee/schemas/common/comments.json
> +    "additionalProperties": false,
We should remove this

2021-07-22 17:54 UTC, luandy64 commented on tests/base.py
> +                continue
Seems like this used to have a newline, we should put it back

2021-07-22 17:59 UTC, luandy64 approved these changes

2021-07-22 18:05 UTC, merged